package domain

import (
	"time"

	"github.com/google/uuid"
)

// StrategyTags contains classification tags for a strategy.
type StrategyTags struct {
	StrategyType []string `json:"strategy_type,omitempty"` // e.g., "trend_following", "momentum", "mean_reversion"
	RiskLevel    string   `json:"risk_level,omitempty"`    // "low", "medium", "high"
	TradingStyle string   `json:"trading_style,omitempty"` // "scalping", "intraday", "swing", "position"
	Indicators   []string `json:"indicators,omitempty"`    // Detected indicators from code
	MarketRegime []string `json:"market_regime,omitempty"` // "trending", "ranging", "volatile" - added by Analyst
}

// Strategy represents a trading strategy.
type Strategy struct {
	ID          uuid.UUID  `json:"id"`
	Name        string     `json:"name"`
	Code        string     `json:"code"`
	CodeHash    string     `json:"code_hash"`
	ParentID    *uuid.UUID `json:"parent_id,omitempty"`
	Generation  int        `json:"generation"`
	Description string     `json:"description,omitempty"`

	// Classification tags (generated by LLM)
	Tags                   *StrategyTags `json:"tags,omitempty"`
	DescriptionGeneratedAt *time.Time    `json:"description_generated_at,omitempty"`

	// Metadata (provided by Python Agent)
	Timeframe                  string             `json:"timeframe,omitempty"`
	Stoploss                   *float64           `json:"stoploss,omitempty"`
	TrailingStop               bool               `json:"trailing_stop"`
	TrailingStopPositive       *float64           `json:"trailing_stop_positive,omitempty"`
	TrailingStopPositiveOffset *float64           `json:"trailing_stop_positive_offset,omitempty"`
	StartupCandleCount         *int               `json:"startup_candle_count,omitempty"`
	Indicators                 []string           `json:"indicators,omitempty"`
	MinimalROI                 map[string]float64 `json:"minimal_roi,omitempty"`

	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// NewStrategy creates a new Strategy with generated UUID and timestamps.
func NewStrategy(name, code, description string, parentID *uuid.UUID) *Strategy {
	now := time.Now()
	return &Strategy{
		ID:          uuid.New(),
		Name:        name,
		Code:        code,
		Description: description,
		ParentID:    parentID,
		Generation:  0, // Will be set by database trigger
		Indicators:  make([]string, 0),
		MinimalROI:  make(map[string]float64),
		CreatedAt:   now,
		UpdatedAt:   now,
	}
}

// StrategyWithMetrics combines a strategy with its best performance metrics.
type StrategyWithMetrics struct {
	Strategy   *Strategy                   `json:"strategy"`
	BestResult *StrategyPerformanceMetrics `json:"best_result,omitempty"`
}

// StrategyPerformanceMetrics represents aggregated performance metrics for a strategy.
type StrategyPerformanceMetrics struct {
	SharpeRatio    *float64 `json:"sharpe_ratio,omitempty"`
	SortinoRatio   *float64 `json:"sortino_ratio,omitempty"`
	ProfitPct      float64  `json:"profit_pct"`
	MaxDrawdownPct float64  `json:"max_drawdown_pct"`
	TotalTrades    int      `json:"total_trades"`
	WinRate        float64  `json:"win_rate"`
	BacktestCount  int      `json:"backtest_count"`
}

// StrategyLineageNode represents a node in the strategy lineage tree.
type StrategyLineageNode struct {
	ID         uuid.UUID              `json:"id"`
	Name       string                 `json:"name"`
	Generation int                    `json:"generation"`
	ParentID   *uuid.UUID             `json:"parent_id,omitempty"`
	Children   []*StrategyLineageNode `json:"children,omitempty"`
	Level      int                    `json:"level"` // Distance from the queried node
}

// StrategySearchQuery represents query parameters for searching strategies.
type StrategySearchQuery struct {
	NamePattern    *string  `json:"name_pattern,omitempty"`
	MinSharpe      *float64 `json:"min_sharpe,omitempty"`
	MinProfitPct   *float64 `json:"min_profit_pct,omitempty"`
	MaxDrawdownPct *float64 `json:"max_drawdown_pct,omitempty"`
	MinTrades      *int     `json:"min_trades,omitempty"`
	MinGeneration  *int     `json:"min_generation,omitempty"`
	MaxGeneration  *int     `json:"max_generation,omitempty"`
	ParentID       *string  `json:"parent_id,omitempty"`
	OrderBy        string   `json:"order_by,omitempty"` // "sharpe", "profit", "created_at", "generation"
	Ascending      bool     `json:"ascending,omitempty"`
	Page           int      `json:"page"`
	PageSize       int      `json:"page_size"`
}

// SetDefaults sets default values for the search query.
func (q *StrategySearchQuery) SetDefaults() {
	if q.OrderBy == "" {
		q.OrderBy = "created_at"
	}
	if q.Page <= 0 {
		q.Page = 1
	}
	if q.PageSize <= 0 {
		q.PageSize = 20
	}
	if q.PageSize > 100 {
		q.PageSize = 100
	}
}

// Offset returns the offset for pagination.
func (q *StrategySearchQuery) Offset() int {
	return (q.Page - 1) * q.PageSize
}
