"""Event schemas for RabbitMQ messages."""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


class BaseEvent(BaseModel):
    """Base class for all events."""

    event_id: str = ""  # UUID
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    source: str = "python-agents"


class StrategyDiscoveredEvent(BaseEvent):
    """Event: A new strategy was discovered by Scout Agent."""

    # Strategy info
    name: str
    source_type: str  # "stratninja", "github", etc.
    source_url: str

    # Code
    code: str
    code_hash: str

    # Metadata
    detected_indicators: list[str] = Field(default_factory=list)
    timeframe: str | None = None
    stoploss: float | None = None

    # Validation
    is_valid: bool
    validation_errors: list[str] = Field(default_factory=list)


class StrategyReadyEvent(BaseEvent):
    """Event: Strategy is ready for backtesting."""

    # Strategy identity
    strategy_id: str
    strategy_name: str

    # Code
    code: str
    code_hash: str

    # Metadata (generated by Engineer Agent)
    description: str = ""
    tags: dict[str, Any] = Field(default_factory=dict)

    # Hyperopt config
    hyperopt_config: dict[str, Any] | None = None

    # Lineage
    parent_id: str | None = None
    generation: int = 0


class BacktestCompletedEvent(BaseEvent):
    """Event: Backtest job completed."""

    # Job info
    job_id: str
    strategy_id: str
    strategy_name: str

    # Status
    success: bool
    error_message: str | None = None

    # Results (if success)
    total_trades: int | None = None
    profit_pct: float | None = None
    win_rate: float | None = None
    max_drawdown_pct: float | None = None
    sharpe_ratio: float | None = None

    # Full result reference
    result_id: str | None = None


class StrategyEvolveEvent(BaseEvent):
    """Event: Strategy needs evolution based on diagnosis."""

    # Strategy info
    strategy_id: str
    strategy_name: str
    current_code: str

    # Diagnosis reference
    diagnosis_job_id: str

    # Modification instructions
    suggestion_type: str
    suggestion_description: str
    target_metrics: list[str] = Field(default_factory=list)

    # Context
    previous_metrics: dict[str, float] = Field(default_factory=dict)


class StrategyApprovedEvent(BaseEvent):
    """Event: Strategy approved for live trading."""

    strategy_id: str
    strategy_name: str

    # Performance summary
    profit_pct: float
    win_rate: float
    max_drawdown_pct: float
    sharpe_ratio: float | None = None

    # Enhanced description (appended with performance summary)
    enhanced_description: str | None = None

    # Market regime tags (added by Analyst based on performance)
    market_regime: list[str] = Field(default_factory=list)

    # Approval details
    confidence: float
    approved_for_pairs: list[str] = Field(default_factory=list)
    approved_timeframe: str | None = None


class StrategyArchivedEvent(BaseEvent):
    """Event: Strategy archived (discarded)."""

    strategy_id: str
    strategy_name: str
    reason: str
    final_metrics: dict[str, float] = Field(default_factory=dict)


class AgentHeartbeatEvent(BaseEvent):
    """Event: Agent heartbeat for status monitoring."""

    agent_type: str  # orchestrator, engineer, analyst, scout
    status: str  # active, idle
    current_task: str | None = None


class ScoutProgressEvent(BaseEvent):
    """Event: Scout Agent progress update."""

    run_id: str
    stage: str  # "fetch", "validate", "deduplicate", "submit"
    progress: int  # 0-100
    message: str
    stage_metrics: dict[str, int] = Field(default_factory=dict)


class ScoutCompletedEvent(BaseEvent):
    """Event: Scout Agent run completed successfully."""

    run_id: str
    total_fetched: int
    validated: int
    validation_failed: int
    duplicates_removed: int
    submitted: int


class ScoutFailedEvent(BaseEvent):
    """Event: Scout Agent run failed."""

    run_id: str
    error_message: str
    stage: str | None = None
