"""Strategy-related Pydantic schemas."""

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class StrategySource(str, Enum):
    """Known strategy data sources."""

    STRATNINJA = "stratninja"
    GITHUB = "github"
    TRADINGVIEW = "tradingview"
    MANUAL = "manual"


class StrategyType(str, Enum):
    """Strategy classification types."""

    TREND_FOLLOWING = "trend_following"
    MOMENTUM = "momentum"
    MEAN_REVERSION = "mean_reversion"
    GRID = "grid"
    BREAKOUT = "breakout"
    SCALPING = "scalping"
    SWING = "swing"


class RiskLevel(str, Enum):
    """Strategy risk level classification."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class TradingStyle(str, Enum):
    """Trading style/timeframe classification."""

    SCALPING = "scalping"
    INTRADAY = "intraday"
    SWING = "swing"
    POSITION = "position"


class StrategyTags(BaseModel):
    """Classification tags for a strategy.

    Generated by LLM analysis of strategy code.
    """

    strategy_type: list[str] = Field(
        default_factory=list,
        description="Strategy types: trend_following, momentum, mean_reversion, grid, breakout",
    )
    risk_level: RiskLevel | None = Field(
        default=None,
        description="Risk level based on stoploss and drawdown: low, medium, high",
    )
    trading_style: TradingStyle | None = Field(
        default=None,
        description="Trading style based on timeframe: scalping, intraday, swing, position",
    )
    indicators: list[str] = Field(
        default_factory=list,
        description="Indicators detected in the strategy code",
    )
    market_regime: list[str] = Field(
        default_factory=list,
        description="Suitable market regimes: trending, ranging, volatile (added by Analyst)",
    )


class RawStrategy(BaseModel):
    """A raw strategy fetched from a data source.

    This represents the initial discovery before any processing.
    """

    # Source information
    source: StrategySource
    source_url: str
    source_name: str = ""  # e.g., repo name for GitHub

    # Basic info
    name: str
    description: str | None = None

    # Code
    code: str
    code_hash: str = ""  # SimHash for deduplication

    # Extracted metadata
    detected_indicators: list[str] = Field(default_factory=list)
    timeframe: str | None = None
    stoploss: float | None = None

    # Parse results
    is_valid: bool = False
    validation_errors: list[str] = Field(default_factory=list)
    missing_methods: list[str] = Field(default_factory=list)

    # Tracking
    discovered_at: datetime = Field(default_factory=datetime.utcnow)


class StrategyParameter(BaseModel):
    """A hyperparameter for optimization."""

    name: str
    param_type: str  # "int" | "float" | "bool" | "categorical"
    default: float | int | bool | str
    low: float | int | None = None
    high: float | int | None = None
    choices: list[Any] | None = None  # For categorical
    space: str = "buy"  # "buy" | "sell" | "roi" | "stoploss" | "protection"


class HyperoptConfig(BaseModel):
    """Configuration for hyperparameter optimization."""

    parameters: list[StrategyParameter] = Field(default_factory=list)

    # Search settings
    epochs: int = 100
    spaces: list[str] = Field(default_factory=lambda: ["buy", "sell"])

    # Loss function
    loss_function: str = "SharpeHyperOptLoss"


class ExecutableStrategy(BaseModel):
    """A strategy ready for backtesting.

    This is the output of the Engineer Agent.
    """

    # Identity
    id: str | None = None  # UUID assigned by Go backend
    name: str
    code: str
    code_hash: str

    # Lineage
    parent_id: str | None = None  # For evolved strategies
    generation: int = 0
    source_strategy_id: str | None = None  # Original raw strategy

    # Metadata
    description: str | None = None
    timeframe: str | None = None
    indicators: list[str] = Field(default_factory=list)

    # Classification tags (generated by LLM)
    tags: StrategyTags = Field(default_factory=StrategyTags)

    # Hyperopt configuration
    hyperopt_config: HyperoptConfig | None = None

    # Processing info
    created_at: datetime = Field(default_factory=datetime.utcnow)
    created_by: str = "engineer_agent"
