# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import backtest_pb2 as freqsearch_dot_v1_dot_backtest__pb2
from . import common_pb2 as freqsearch_dot_v1_dot_common__pb2
from . import freqsearch_pb2 as freqsearch_dot_v1_dot_freqsearch__pb2
from . import strategy_pb2 as freqsearch_dot_v1_dot_strategy__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.74.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in freqsearch/v1/freqsearch_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FreqSearchServiceStub(object):
    """----- Main Service Definition -----

    ===== Strategy Operations =====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateStrategy = channel.unary_unary(
                '/freqsearch.v1.FreqSearchService/CreateStrategy',
                request_serializer=freqsearch_dot_v1_dot_strategy__pb2.CreateStrategyRequest.SerializeToString,
                response_deserializer=freqsearch_dot_v1_dot_strategy__pb2.CreateStrategyResponse.FromString,
                _registered_method=True)
        self.GetStrategy = channel.unary_unary(
                '/freqsearch.v1.FreqSearchService/GetStrategy',
                request_serializer=freqsearch_dot_v1_dot_strategy__pb2.GetStrategyRequest.SerializeToString,
                response_deserializer=freqsearch_dot_v1_dot_strategy__pb2.GetStrategyResponse.FromString,
                _registered_method=True)
        self.SearchStrategies = channel.unary_unary(
                '/freqsearch.v1.FreqSearchService/SearchStrategies',
                request_serializer=freqsearch_dot_v1_dot_strategy__pb2.SearchStrategiesRequest.SerializeToString,
                response_deserializer=freqsearch_dot_v1_dot_strategy__pb2.SearchStrategiesResponse.FromString,
                _registered_method=True)
        self.GetStrategyLineage = channel.unary_unary(
                '/freqsearch.v1.FreqSearchService/GetStrategyLineage',
                request_serializer=freqsearch_dot_v1_dot_strategy__pb2.GetStrategyLineageRequest.SerializeToString,
                response_deserializer=freqsearch_dot_v1_dot_strategy__pb2.GetStrategyLineageResponse.FromString,
                _registered_method=True)
        self.DeleteStrategy = channel.unary_unary(
                '/freqsearch.v1.FreqSearchService/DeleteStrategy',
                request_serializer=freqsearch_dot_v1_dot_strategy__pb2.DeleteStrategyRequest.SerializeToString,
                response_deserializer=freqsearch_dot_v1_dot_strategy__pb2.DeleteStrategyResponse.FromString,
                _registered_method=True)
        self.ValidateStrategy = channel.unary_unary(
                '/freqsearch.v1.FreqSearchService/ValidateStrategy',
                request_serializer=freqsearch_dot_v1_dot_strategy__pb2.ValidateStrategyRequest.SerializeToString,
                response_deserializer=freqsearch_dot_v1_dot_strategy__pb2.ValidateStrategyResponse.FromString,
                _registered_method=True)
        self.SubmitBacktest = channel.unary_unary(
                '/freqsearch.v1.FreqSearchService/SubmitBacktest',
                request_serializer=freqsearch_dot_v1_dot_backtest__pb2.SubmitBacktestRequest.SerializeToString,
                response_deserializer=freqsearch_dot_v1_dot_backtest__pb2.SubmitBacktestResponse.FromString,
                _registered_method=True)
        self.SubmitBatchBacktest = channel.unary_unary(
                '/freqsearch.v1.FreqSearchService/SubmitBatchBacktest',
                request_serializer=freqsearch_dot_v1_dot_backtest__pb2.SubmitBatchBacktestRequest.SerializeToString,
                response_deserializer=freqsearch_dot_v1_dot_backtest__pb2.SubmitBatchBacktestResponse.FromString,
                _registered_method=True)
        self.GetBacktestJob = channel.unary_unary(
                '/freqsearch.v1.FreqSearchService/GetBacktestJob',
                request_serializer=freqsearch_dot_v1_dot_backtest__pb2.GetBacktestJobRequest.SerializeToString,
                response_deserializer=freqsearch_dot_v1_dot_backtest__pb2.GetBacktestJobResponse.FromString,
                _registered_method=True)
        self.GetBacktestResult = channel.unary_unary(
                '/freqsearch.v1.FreqSearchService/GetBacktestResult',
                request_serializer=freqsearch_dot_v1_dot_backtest__pb2.GetBacktestResultRequest.SerializeToString,
                response_deserializer=freqsearch_dot_v1_dot_backtest__pb2.GetBacktestResultResponse.FromString,
                _registered_method=True)
        self.QueryBacktestResults = channel.unary_unary(
                '/freqsearch.v1.FreqSearchService/QueryBacktestResults',
                request_serializer=freqsearch_dot_v1_dot_backtest__pb2.QueryBacktestResultsRequest.SerializeToString,
                response_deserializer=freqsearch_dot_v1_dot_backtest__pb2.QueryBacktestResultsResponse.FromString,
                _registered_method=True)
        self.CancelBacktest = channel.unary_unary(
                '/freqsearch.v1.FreqSearchService/CancelBacktest',
                request_serializer=freqsearch_dot_v1_dot_backtest__pb2.CancelBacktestRequest.SerializeToString,
                response_deserializer=freqsearch_dot_v1_dot_backtest__pb2.CancelBacktestResponse.FromString,
                _registered_method=True)
        self.GetQueueStats = channel.unary_unary(
                '/freqsearch.v1.FreqSearchService/GetQueueStats',
                request_serializer=freqsearch_dot_v1_dot_backtest__pb2.GetQueueStatsRequest.SerializeToString,
                response_deserializer=freqsearch_dot_v1_dot_backtest__pb2.GetQueueStatsResponse.FromString,
                _registered_method=True)
        self.StartOptimization = channel.unary_unary(
                '/freqsearch.v1.FreqSearchService/StartOptimization',
                request_serializer=freqsearch_dot_v1_dot_freqsearch__pb2.StartOptimizationRequest.SerializeToString,
                response_deserializer=freqsearch_dot_v1_dot_freqsearch__pb2.StartOptimizationResponse.FromString,
                _registered_method=True)
        self.GetOptimizationRun = channel.unary_unary(
                '/freqsearch.v1.FreqSearchService/GetOptimizationRun',
                request_serializer=freqsearch_dot_v1_dot_freqsearch__pb2.GetOptimizationRunRequest.SerializeToString,
                response_deserializer=freqsearch_dot_v1_dot_freqsearch__pb2.GetOptimizationRunResponse.FromString,
                _registered_method=True)
        self.ControlOptimization = channel.unary_unary(
                '/freqsearch.v1.FreqSearchService/ControlOptimization',
                request_serializer=freqsearch_dot_v1_dot_freqsearch__pb2.ControlOptimizationRequest.SerializeToString,
                response_deserializer=freqsearch_dot_v1_dot_freqsearch__pb2.ControlOptimizationResponse.FromString,
                _registered_method=True)
        self.ListOptimizationRuns = channel.unary_unary(
                '/freqsearch.v1.FreqSearchService/ListOptimizationRuns',
                request_serializer=freqsearch_dot_v1_dot_freqsearch__pb2.ListOptimizationRunsRequest.SerializeToString,
                response_deserializer=freqsearch_dot_v1_dot_freqsearch__pb2.ListOptimizationRunsResponse.FromString,
                _registered_method=True)
        self.UpdateIterationResult = channel.unary_unary(
                '/freqsearch.v1.FreqSearchService/UpdateIterationResult',
                request_serializer=freqsearch_dot_v1_dot_freqsearch__pb2.UpdateIterationResultRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateIterationFeedback = channel.unary_unary(
                '/freqsearch.v1.FreqSearchService/UpdateIterationFeedback',
                request_serializer=freqsearch_dot_v1_dot_freqsearch__pb2.UpdateIterationFeedbackRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/freqsearch.v1.FreqSearchService/HealthCheck',
                request_serializer=freqsearch_dot_v1_dot_common__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=freqsearch_dot_v1_dot_common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class FreqSearchServiceServicer(object):
    """----- Main Service Definition -----

    ===== Strategy Operations =====
    """

    def CreateStrategy(self, request, context):
        """Create a new strategy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStrategy(self, request, context):
        """Get strategy by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchStrategies(self, request, context):
        """Search strategies with filters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStrategyLineage(self, request, context):
        """Get strategy evolution lineage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteStrategy(self, request, context):
        """Delete a strategy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateStrategy(self, request, context):
        """Validate strategy code using Docker container (fast validation without full backtest)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitBacktest(self, request, context):
        """===== Backtest Operations =====

        Submit a single backtest job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitBatchBacktest(self, request, context):
        """Submit multiple backtest jobs (for grid search)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBacktestJob(self, request, context):
        """Get backtest job status and result
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBacktestResult(self, request, context):
        """Get backtest result only
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryBacktestResults(self, request, context):
        """Query backtest results with filters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelBacktest(self, request, context):
        """Cancel a pending/running backtest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueueStats(self, request, context):
        """Get queue statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartOptimization(self, request, context):
        """===== Optimization Operations =====

        Start a new AI optimization run
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOptimizationRun(self, request, context):
        """Get optimization run details with iterations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlOptimization(self, request, context):
        """Control optimization (pause/resume/cancel)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOptimizationRuns(self, request, context):
        """List optimization runs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateIterationResult(self, request, context):
        """Update iteration result
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateIterationFeedback(self, request, context):
        """Update iteration feedback
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """===== Health =====

        Health check endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FreqSearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStrategy,
                    request_deserializer=freqsearch_dot_v1_dot_strategy__pb2.CreateStrategyRequest.FromString,
                    response_serializer=freqsearch_dot_v1_dot_strategy__pb2.CreateStrategyResponse.SerializeToString,
            ),
            'GetStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStrategy,
                    request_deserializer=freqsearch_dot_v1_dot_strategy__pb2.GetStrategyRequest.FromString,
                    response_serializer=freqsearch_dot_v1_dot_strategy__pb2.GetStrategyResponse.SerializeToString,
            ),
            'SearchStrategies': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchStrategies,
                    request_deserializer=freqsearch_dot_v1_dot_strategy__pb2.SearchStrategiesRequest.FromString,
                    response_serializer=freqsearch_dot_v1_dot_strategy__pb2.SearchStrategiesResponse.SerializeToString,
            ),
            'GetStrategyLineage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStrategyLineage,
                    request_deserializer=freqsearch_dot_v1_dot_strategy__pb2.GetStrategyLineageRequest.FromString,
                    response_serializer=freqsearch_dot_v1_dot_strategy__pb2.GetStrategyLineageResponse.SerializeToString,
            ),
            'DeleteStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteStrategy,
                    request_deserializer=freqsearch_dot_v1_dot_strategy__pb2.DeleteStrategyRequest.FromString,
                    response_serializer=freqsearch_dot_v1_dot_strategy__pb2.DeleteStrategyResponse.SerializeToString,
            ),
            'ValidateStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateStrategy,
                    request_deserializer=freqsearch_dot_v1_dot_strategy__pb2.ValidateStrategyRequest.FromString,
                    response_serializer=freqsearch_dot_v1_dot_strategy__pb2.ValidateStrategyResponse.SerializeToString,
            ),
            'SubmitBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitBacktest,
                    request_deserializer=freqsearch_dot_v1_dot_backtest__pb2.SubmitBacktestRequest.FromString,
                    response_serializer=freqsearch_dot_v1_dot_backtest__pb2.SubmitBacktestResponse.SerializeToString,
            ),
            'SubmitBatchBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitBatchBacktest,
                    request_deserializer=freqsearch_dot_v1_dot_backtest__pb2.SubmitBatchBacktestRequest.FromString,
                    response_serializer=freqsearch_dot_v1_dot_backtest__pb2.SubmitBatchBacktestResponse.SerializeToString,
            ),
            'GetBacktestJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBacktestJob,
                    request_deserializer=freqsearch_dot_v1_dot_backtest__pb2.GetBacktestJobRequest.FromString,
                    response_serializer=freqsearch_dot_v1_dot_backtest__pb2.GetBacktestJobResponse.SerializeToString,
            ),
            'GetBacktestResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBacktestResult,
                    request_deserializer=freqsearch_dot_v1_dot_backtest__pb2.GetBacktestResultRequest.FromString,
                    response_serializer=freqsearch_dot_v1_dot_backtest__pb2.GetBacktestResultResponse.SerializeToString,
            ),
            'QueryBacktestResults': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryBacktestResults,
                    request_deserializer=freqsearch_dot_v1_dot_backtest__pb2.QueryBacktestResultsRequest.FromString,
                    response_serializer=freqsearch_dot_v1_dot_backtest__pb2.QueryBacktestResultsResponse.SerializeToString,
            ),
            'CancelBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelBacktest,
                    request_deserializer=freqsearch_dot_v1_dot_backtest__pb2.CancelBacktestRequest.FromString,
                    response_serializer=freqsearch_dot_v1_dot_backtest__pb2.CancelBacktestResponse.SerializeToString,
            ),
            'GetQueueStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueueStats,
                    request_deserializer=freqsearch_dot_v1_dot_backtest__pb2.GetQueueStatsRequest.FromString,
                    response_serializer=freqsearch_dot_v1_dot_backtest__pb2.GetQueueStatsResponse.SerializeToString,
            ),
            'StartOptimization': grpc.unary_unary_rpc_method_handler(
                    servicer.StartOptimization,
                    request_deserializer=freqsearch_dot_v1_dot_freqsearch__pb2.StartOptimizationRequest.FromString,
                    response_serializer=freqsearch_dot_v1_dot_freqsearch__pb2.StartOptimizationResponse.SerializeToString,
            ),
            'GetOptimizationRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOptimizationRun,
                    request_deserializer=freqsearch_dot_v1_dot_freqsearch__pb2.GetOptimizationRunRequest.FromString,
                    response_serializer=freqsearch_dot_v1_dot_freqsearch__pb2.GetOptimizationRunResponse.SerializeToString,
            ),
            'ControlOptimization': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlOptimization,
                    request_deserializer=freqsearch_dot_v1_dot_freqsearch__pb2.ControlOptimizationRequest.FromString,
                    response_serializer=freqsearch_dot_v1_dot_freqsearch__pb2.ControlOptimizationResponse.SerializeToString,
            ),
            'ListOptimizationRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOptimizationRuns,
                    request_deserializer=freqsearch_dot_v1_dot_freqsearch__pb2.ListOptimizationRunsRequest.FromString,
                    response_serializer=freqsearch_dot_v1_dot_freqsearch__pb2.ListOptimizationRunsResponse.SerializeToString,
            ),
            'UpdateIterationResult': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateIterationResult,
                    request_deserializer=freqsearch_dot_v1_dot_freqsearch__pb2.UpdateIterationResultRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateIterationFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateIterationFeedback,
                    request_deserializer=freqsearch_dot_v1_dot_freqsearch__pb2.UpdateIterationFeedbackRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=freqsearch_dot_v1_dot_common__pb2.HealthCheckRequest.FromString,
                    response_serializer=freqsearch_dot_v1_dot_common__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'freqsearch.v1.FreqSearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('freqsearch.v1.FreqSearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FreqSearchService(object):
    """----- Main Service Definition -----

    ===== Strategy Operations =====
    """

    @staticmethod
    def CreateStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freqsearch.v1.FreqSearchService/CreateStrategy',
            freqsearch_dot_v1_dot_strategy__pb2.CreateStrategyRequest.SerializeToString,
            freqsearch_dot_v1_dot_strategy__pb2.CreateStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freqsearch.v1.FreqSearchService/GetStrategy',
            freqsearch_dot_v1_dot_strategy__pb2.GetStrategyRequest.SerializeToString,
            freqsearch_dot_v1_dot_strategy__pb2.GetStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchStrategies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freqsearch.v1.FreqSearchService/SearchStrategies',
            freqsearch_dot_v1_dot_strategy__pb2.SearchStrategiesRequest.SerializeToString,
            freqsearch_dot_v1_dot_strategy__pb2.SearchStrategiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStrategyLineage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freqsearch.v1.FreqSearchService/GetStrategyLineage',
            freqsearch_dot_v1_dot_strategy__pb2.GetStrategyLineageRequest.SerializeToString,
            freqsearch_dot_v1_dot_strategy__pb2.GetStrategyLineageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freqsearch.v1.FreqSearchService/DeleteStrategy',
            freqsearch_dot_v1_dot_strategy__pb2.DeleteStrategyRequest.SerializeToString,
            freqsearch_dot_v1_dot_strategy__pb2.DeleteStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freqsearch.v1.FreqSearchService/ValidateStrategy',
            freqsearch_dot_v1_dot_strategy__pb2.ValidateStrategyRequest.SerializeToString,
            freqsearch_dot_v1_dot_strategy__pb2.ValidateStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freqsearch.v1.FreqSearchService/SubmitBacktest',
            freqsearch_dot_v1_dot_backtest__pb2.SubmitBacktestRequest.SerializeToString,
            freqsearch_dot_v1_dot_backtest__pb2.SubmitBacktestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitBatchBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freqsearch.v1.FreqSearchService/SubmitBatchBacktest',
            freqsearch_dot_v1_dot_backtest__pb2.SubmitBatchBacktestRequest.SerializeToString,
            freqsearch_dot_v1_dot_backtest__pb2.SubmitBatchBacktestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBacktestJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freqsearch.v1.FreqSearchService/GetBacktestJob',
            freqsearch_dot_v1_dot_backtest__pb2.GetBacktestJobRequest.SerializeToString,
            freqsearch_dot_v1_dot_backtest__pb2.GetBacktestJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBacktestResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freqsearch.v1.FreqSearchService/GetBacktestResult',
            freqsearch_dot_v1_dot_backtest__pb2.GetBacktestResultRequest.SerializeToString,
            freqsearch_dot_v1_dot_backtest__pb2.GetBacktestResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryBacktestResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freqsearch.v1.FreqSearchService/QueryBacktestResults',
            freqsearch_dot_v1_dot_backtest__pb2.QueryBacktestResultsRequest.SerializeToString,
            freqsearch_dot_v1_dot_backtest__pb2.QueryBacktestResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freqsearch.v1.FreqSearchService/CancelBacktest',
            freqsearch_dot_v1_dot_backtest__pb2.CancelBacktestRequest.SerializeToString,
            freqsearch_dot_v1_dot_backtest__pb2.CancelBacktestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQueueStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freqsearch.v1.FreqSearchService/GetQueueStats',
            freqsearch_dot_v1_dot_backtest__pb2.GetQueueStatsRequest.SerializeToString,
            freqsearch_dot_v1_dot_backtest__pb2.GetQueueStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartOptimization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freqsearch.v1.FreqSearchService/StartOptimization',
            freqsearch_dot_v1_dot_freqsearch__pb2.StartOptimizationRequest.SerializeToString,
            freqsearch_dot_v1_dot_freqsearch__pb2.StartOptimizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOptimizationRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freqsearch.v1.FreqSearchService/GetOptimizationRun',
            freqsearch_dot_v1_dot_freqsearch__pb2.GetOptimizationRunRequest.SerializeToString,
            freqsearch_dot_v1_dot_freqsearch__pb2.GetOptimizationRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlOptimization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freqsearch.v1.FreqSearchService/ControlOptimization',
            freqsearch_dot_v1_dot_freqsearch__pb2.ControlOptimizationRequest.SerializeToString,
            freqsearch_dot_v1_dot_freqsearch__pb2.ControlOptimizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOptimizationRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freqsearch.v1.FreqSearchService/ListOptimizationRuns',
            freqsearch_dot_v1_dot_freqsearch__pb2.ListOptimizationRunsRequest.SerializeToString,
            freqsearch_dot_v1_dot_freqsearch__pb2.ListOptimizationRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateIterationResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freqsearch.v1.FreqSearchService/UpdateIterationResult',
            freqsearch_dot_v1_dot_freqsearch__pb2.UpdateIterationResultRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateIterationFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freqsearch.v1.FreqSearchService/UpdateIterationFeedback',
            freqsearch_dot_v1_dot_freqsearch__pb2.UpdateIterationFeedbackRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freqsearch.v1.FreqSearchService/HealthCheck',
            freqsearch_dot_v1_dot_common__pb2.HealthCheckRequest.SerializeToString,
            freqsearch_dot_v1_dot_common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
