"""
WorldQuant 101 Formulaic Alphas
================================

Complete dataset of 101 alpha factors from WorldQuant's paper:
"101 Formulaic Alphas" by Zura Kakushadze

Each factor is classified across 6 dimensions:
- category: momentum, mean_reversion, volatility, volume, price_pattern
- signal_type: entry, exit, filter, sizing, alpha
- holding_period: intraday, short (1-3d), medium (3-10d), long (10d+)
- data_requirement: price_only, volume, vwap, industry, fundamental
- market_regime: trending, ranging, volatile, any
- complexity: simple, medium, complex

Reference implementation: https://github.com/yli188/WorldQuant_alpha101_code
"""

WQ101_FACTORS = [
    {
        "name": "alpha_001",
        "source": "worldquant_101",
        "expression": "(rank(Ts_ArgMax(SignedPower(((returns < 0) ? stddev(returns, 20) : close), 2.), 5)) - 0.5)",
        "description": "动量反转因子，在负收益时使用波动率，正收益时使用价格，通过最大值位置的排名检测趋势强度",
        "category": "momentum",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "price_only",
        "market_regime": "volatile",
        "complexity": "complex",
        "operator_deps": ["rank", "ts_argmax", "signed_power", "stddev", "returns"],
        "data_deps": ["close", "returns"]
    },
    {
        "name": "alpha_002",
        "source": "worldquant_101",
        "expression": "(-1 * correlation(rank(delta(log(volume), 2)), rank(((close - open) / open)), 6))",
        "description": "价量背离因子，成交量变化与日内收益率的负相关性，捕捉异常交易行为",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "any",
        "complexity": "medium",
        "operator_deps": ["correlation", "rank", "delta", "log"],
        "data_deps": ["volume", "close", "open"]
    },
    {
        "name": "alpha_003",
        "source": "worldquant_101",
        "expression": "(-1 * correlation(rank(open), rank(volume), 10))",
        "description": "开盘价与成交量负相关，识别价格操纵或异常交易模式",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "any",
        "complexity": "simple",
        "operator_deps": ["correlation", "rank"],
        "data_deps": ["open", "volume"]
    },
    {
        "name": "alpha_004",
        "source": "worldquant_101",
        "expression": "(-1 * Ts_Rank(rank(low), 9))",
        "description": "低价时序排名反转，检测短期超卖后的反弹机会",
        "category": "mean_reversion",
        "signal_type": "entry",
        "holding_period": "short",
        "data_requirement": "price_only",
        "market_regime": "ranging",
        "complexity": "simple",
        "operator_deps": ["ts_rank", "rank"],
        "data_deps": ["low"]
    },
    {
        "name": "alpha_005",
        "source": "worldquant_101",
        "expression": "(rank((open - (sum(vwap, 10) / 10))) * (-1 * abs(rank((close - vwap)))))",
        "description": "开盘价相对VWAP偏离与收盘价相对VWAP偏离的组合，识别价格回归均值的机会",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "vwap",
        "market_regime": "ranging",
        "complexity": "medium",
        "operator_deps": ["rank", "sum", "abs"],
        "data_deps": ["open", "close", "vwap"]
    },
    {
        "name": "alpha_006",
        "source": "worldquant_101",
        "expression": "(-1 * correlation(open, volume, 10))",
        "description": "开盘价与成交量的负相关性，捕捉异常的价量关系",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "any",
        "complexity": "simple",
        "operator_deps": ["correlation"],
        "data_deps": ["open", "volume"]
    },
    {
        "name": "alpha_007",
        "source": "worldquant_101",
        "expression": "((adv20 < volume) ? ((-1 * ts_rank(abs(delta(close, 7)), 60)) * sign(delta(close, 7))) : (-1 * 1))",
        "description": "成交量突破时的价格动量，7日价格变化幅度的时序排名反转",
        "category": "momentum",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "volume",
        "market_regime": "trending",
        "complexity": "complex",
        "operator_deps": ["ts_rank", "abs", "delta", "sign"],
        "data_deps": ["close", "volume", "adv20"]
    },
    {
        "name": "alpha_008",
        "source": "worldquant_101",
        "expression": "(-1 * rank(((sum(open, 5) * sum(returns, 5)) - delay((sum(open, 5) * sum(returns, 5)), 10))))",
        "description": "开盘价与收益率乘积的动量，检测价格趋势的强度变化",
        "category": "momentum",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "price_only",
        "market_regime": "trending",
        "complexity": "medium",
        "operator_deps": ["rank", "sum", "delay"],
        "data_deps": ["open", "returns"]
    },
    {
        "name": "alpha_009",
        "source": "worldquant_101",
        "expression": "((0 < ts_min(delta(close, 1), 5)) ? delta(close, 1) : ((ts_max(delta(close, 1), 5) < 0) ? delta(close, 1) : (-1 * delta(close, 1))))",
        "description": "趋势延续因子，根据5日最小/最大价格变化判断趋势方向",
        "category": "momentum",
        "signal_type": "entry",
        "holding_period": "short",
        "data_requirement": "price_only",
        "market_regime": "trending",
        "complexity": "medium",
        "operator_deps": ["ts_min", "ts_max", "delta"],
        "data_deps": ["close"]
    },
    {
        "name": "alpha_010",
        "source": "worldquant_101",
        "expression": "rank(((0 < ts_min(delta(close, 1), 4)) ? delta(close, 1) : ((ts_max(delta(close, 1), 4) < 0) ? delta(close, 1) : (-1 * delta(close, 1)))))",
        "description": "趋势强度排名，类似alpha_009但使用4日窗口并排名",
        "category": "momentum",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "price_only",
        "market_regime": "trending",
        "complexity": "medium",
        "operator_deps": ["rank", "ts_min", "ts_max", "delta"],
        "data_deps": ["close"]
    },
    {
        "name": "alpha_011",
        "source": "worldquant_101",
        "expression": "((rank(ts_max((vwap - close), 3)) + rank(ts_min((vwap - close), 3))) * rank(delta(volume, 3)))",
        "description": "VWAP偏离极值与成交量变化的组合，识别价格异常波动",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "vwap",
        "market_regime": "volatile",
        "complexity": "medium",
        "operator_deps": ["rank", "ts_max", "ts_min", "delta"],
        "data_deps": ["vwap", "close", "volume"]
    },
    {
        "name": "alpha_012",
        "source": "worldquant_101",
        "expression": "(sign(delta(volume, 1)) * (-1 * delta(close, 1)))",
        "description": "成交量与价格反向变化，捕捉价量背离信号",
        "category": "mean_reversion",
        "signal_type": "entry",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "any",
        "complexity": "simple",
        "operator_deps": ["sign", "delta"],
        "data_deps": ["volume", "close"]
    },
    {
        "name": "alpha_013",
        "source": "worldquant_101",
        "expression": "(-1 * rank(covariance(rank(close), rank(volume), 5)))",
        "description": "价格排名与成交量排名的协方差，检测异常的价量关系",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "any",
        "complexity": "medium",
        "operator_deps": ["rank", "covariance"],
        "data_deps": ["close", "volume"]
    },
    {
        "name": "alpha_014",
        "source": "worldquant_101",
        "expression": "((-1 * rank(delta(returns, 3))) * correlation(open, volume, 10))",
        "description": "收益率变化与开盘价-成交量相关性的组合",
        "category": "momentum",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "any",
        "complexity": "medium",
        "operator_deps": ["rank", "delta", "correlation"],
        "data_deps": ["returns", "open", "volume"]
    },
    {
        "name": "alpha_015",
        "source": "worldquant_101",
        "expression": "(-1 * sum(rank(correlation(rank(high), rank(volume), 3)), 3))",
        "description": "高价与成交量相关性的滚动求和，识别价格拉升模式",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "trending",
        "complexity": "medium",
        "operator_deps": ["sum", "rank", "correlation"],
        "data_deps": ["high", "volume"]
    },
    {
        "name": "alpha_016",
        "source": "worldquant_101",
        "expression": "(-1 * rank(covariance(rank(high), rank(volume), 5)))",
        "description": "高价与成交量的协方差，类似alpha_013但使用高价",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "any",
        "complexity": "medium",
        "operator_deps": ["rank", "covariance"],
        "data_deps": ["high", "volume"]
    },
    {
        "name": "alpha_017",
        "source": "worldquant_101",
        "expression": "(((-1 * rank(ts_rank(close, 10))) * rank(delta(delta(close, 1), 1))) * rank(ts_rank((volume / adv20), 5)))",
        "description": "价格时序排名、价格加速度与相对成交量的三重组合",
        "category": "momentum",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "trending",
        "complexity": "complex",
        "operator_deps": ["rank", "ts_rank", "delta"],
        "data_deps": ["close", "volume", "adv20"]
    },
    {
        "name": "alpha_018",
        "source": "worldquant_101",
        "expression": "(-1 * rank(((stddev(abs((close - open)), 5) + (close - open)) + correlation(close, open, 10))))",
        "description": "日内波动标准差、价格偏移与收盘-开盘相关性的组合",
        "category": "volatility",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "price_only",
        "market_regime": "volatile",
        "complexity": "medium",
        "operator_deps": ["rank", "stddev", "abs", "correlation"],
        "data_deps": ["close", "open"]
    },
    {
        "name": "alpha_019",
        "source": "worldquant_101",
        "expression": "((-1 * sign(((close - delay(close, 7)) + delta(close, 7)))) * (1 + rank((1 + sum(returns, 250)))))",
        "description": "7日价格变化方向与长期累计收益的组合，趋势反转因子",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "price_only",
        "market_regime": "any",
        "complexity": "medium",
        "operator_deps": ["sign", "delay", "delta", "rank", "sum"],
        "data_deps": ["close", "returns"]
    },
    {
        "name": "alpha_020",
        "source": "worldquant_101",
        "expression": "(((-1 * rank((open - delay(high, 1)))) * rank((open - delay(close, 1)))) * rank((open - delay(low, 1))))",
        "description": "开盘价相对前日高低收的三重排名，识别开盘缺口模式",
        "category": "price_pattern",
        "signal_type": "entry",
        "holding_period": "short",
        "data_requirement": "price_only",
        "market_regime": "trending",
        "complexity": "medium",
        "operator_deps": ["rank", "delay"],
        "data_deps": ["open", "high", "close", "low"]
    },
    {
        "name": "alpha_021",
        "source": "worldquant_101",
        "expression": "((((sum(close, 8) / 8) + stddev(close, 8)) < (sum(close, 2) / 2)) ? (-1 * 1) : (((sum(close, 2) / 2) < ((sum(close, 8) / 8) - stddev(close, 8))) ? 1 : (((1 < (volume / adv20)) || ((volume / adv20) == 1)) ? 1 : (-1 * 1))))",
        "description": "均线突破结合波动率带和成交量确认，综合趋势判断",
        "category": "momentum",
        "signal_type": "entry",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "trending",
        "complexity": "complex",
        "operator_deps": ["sum", "stddev"],
        "data_deps": ["close", "volume", "adv20"]
    },
    {
        "name": "alpha_022",
        "source": "worldquant_101",
        "expression": "(-1 * (delta(correlation(high, volume, 5), 5) * rank(stddev(close, 20))))",
        "description": "高价-成交量相关性变化与价格波动率的组合",
        "category": "volatility",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "volatile",
        "complexity": "medium",
        "operator_deps": ["delta", "correlation", "rank", "stddev"],
        "data_deps": ["high", "volume", "close"]
    },
    {
        "name": "alpha_023",
        "source": "worldquant_101",
        "expression": "(((sum(high, 20) / 20) < high) ? (-1 * delta(high, 2)) : 0)",
        "description": "突破20日均线时的价格动量，趋势确认因子",
        "category": "momentum",
        "signal_type": "entry",
        "holding_period": "medium",
        "data_requirement": "price_only",
        "market_regime": "trending",
        "complexity": "simple",
        "operator_deps": ["sum", "delta"],
        "data_deps": ["high"]
    },
    {
        "name": "alpha_024",
        "source": "worldquant_101",
        "expression": "((((delta((sum(close, 100) / 100), 100) / delay(close, 100)) < 0.05) || ((delta((sum(close, 100) / 100), 100) / delay(close, 100)) == 0.05)) ? (-1 * (close - ts_min(close, 100))) : (-1 * delta(close, 3)))",
        "description": "长期均线变化率阈值判断，低波动时用距离最低价，高波动时用短期动量",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "long",
        "data_requirement": "price_only",
        "market_regime": "ranging",
        "complexity": "complex",
        "operator_deps": ["delta", "sum", "delay", "ts_min"],
        "data_deps": ["close"]
    },
    {
        "name": "alpha_025",
        "source": "worldquant_101",
        "expression": "rank(((((-1 * returns) * adv20) * vwap) * (high - close)))",
        "description": "负收益、成交量、VWAP与上影线的组合，识别卖压",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "vwap",
        "market_regime": "any",
        "complexity": "medium",
        "operator_deps": ["rank"],
        "data_deps": ["returns", "adv20", "vwap", "high", "close"]
    },
    {
        "name": "alpha_026",
        "source": "worldquant_101",
        "expression": "(-1 * ts_max(correlation(ts_rank(volume, 5), ts_rank(high, 5), 5), 3))",
        "description": "成交量与高价时序排名的最大相关性，识别拉升行为",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "trending",
        "complexity": "medium",
        "operator_deps": ["ts_max", "correlation", "ts_rank"],
        "data_deps": ["volume", "high"]
    },
    {
        "name": "alpha_027",
        "source": "worldquant_101",
        "expression": "((0.5 < rank((sum(correlation(rank(volume), rank(vwap), 6), 2) / 2.0))) ? (-1 * 1) : 1)",
        "description": "成交量与VWAP相关性的阈值判断，二元信号",
        "category": "volume",
        "signal_type": "entry",
        "holding_period": "short",
        "data_requirement": "vwap",
        "market_regime": "any",
        "complexity": "medium",
        "operator_deps": ["rank", "sum", "correlation"],
        "data_deps": ["volume", "vwap"]
    },
    {
        "name": "alpha_028",
        "source": "worldquant_101",
        "expression": "scale(((correlation(adv20, low, 5) + ((high + low) / 2)) - close))",
        "description": "成交量与低价相关性、中间价与收盘价偏离的标准化组合",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "any",
        "complexity": "medium",
        "operator_deps": ["scale", "correlation"],
        "data_deps": ["adv20", "low", "high", "close"]
    },
    {
        "name": "alpha_029",
        "source": "worldquant_101",
        "expression": "(min(product(rank(rank(scale(log(sum(ts_min(rank(rank((-1 * rank(delta((close - 1), 5))))), 2), 1))))), 1), 5) + ts_rank(delay((-1 * returns), 6), 5))",
        "description": "多重排名嵌套的价格变化与延迟收益的组合，极复杂因子",
        "category": "momentum",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "price_only",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["min", "product", "rank", "scale", "log", "sum", "ts_min", "delta", "ts_rank", "delay"],
        "data_deps": ["close", "returns"]
    },
    {
        "name": "alpha_030",
        "source": "worldquant_101",
        "expression": "(((1.0 - rank(((sign((close - delay(close, 1))) + sign((delay(close, 1) - delay(close, 2)))) + sign((delay(close, 2) - delay(close, 3)))))) * sum(volume, 5)) / sum(volume, 20))",
        "description": "连续3日价格变化方向一致性与短期/长期成交量比的组合",
        "category": "momentum",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "trending",
        "complexity": "medium",
        "operator_deps": ["rank", "sign", "delay", "sum"],
        "data_deps": ["close", "volume"]
    },
    {
        "name": "alpha_031",
        "source": "worldquant_101",
        "expression": "((rank(rank(rank(decay_linear((-1 * rank(rank(delta(close, 10)))), 10)))) + rank((-1 * delta(close, 3)))) + sign(scale(correlation(adv20, low, 12))))",
        "description": "多重排名的价格变化、短期动量与成交量-低价相关性的组合",
        "category": "momentum",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["rank", "decay_linear", "delta", "sign", "scale", "correlation"],
        "data_deps": ["close", "adv20", "low"]
    },
    {
        "name": "alpha_032",
        "source": "worldquant_101",
        "expression": "(scale(((sum(close, 7) / 7) - close)) + (20 * scale(correlation(vwap, delay(close, 5), 230))))",
        "description": "7日均线偏离与VWAP-延迟收盘价长期相关性的加权组合",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "vwap",
        "market_regime": "ranging",
        "complexity": "medium",
        "operator_deps": ["scale", "sum", "correlation", "delay"],
        "data_deps": ["close", "vwap"]
    },
    {
        "name": "alpha_033",
        "source": "worldquant_101",
        "expression": "rank((-1 * ((1 - (open / close))^1)))",
        "description": "日内收益率的排名，简单的开盘-收盘比率因子",
        "category": "price_pattern",
        "signal_type": "alpha",
        "holding_period": "intraday",
        "data_requirement": "price_only",
        "market_regime": "any",
        "complexity": "simple",
        "operator_deps": ["rank"],
        "data_deps": ["open", "close"]
    },
    {
        "name": "alpha_034",
        "source": "worldquant_101",
        "expression": "rank(((1 - rank((stddev(returns, 2) / stddev(returns, 5)))) + (1 - rank(delta(close, 1)))))",
        "description": "短期/中期波动率比与价格变化的组合，波动率收缩检测",
        "category": "volatility",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "price_only",
        "market_regime": "volatile",
        "complexity": "medium",
        "operator_deps": ["rank", "stddev", "delta"],
        "data_deps": ["returns", "close"]
    },
    {
        "name": "alpha_035",
        "source": "worldquant_101",
        "expression": "((Ts_Rank(volume, 32) * (1 - Ts_Rank(((close + high) - low), 16))) * (1 - Ts_Rank(returns, 32)))",
        "description": "成交量时序排名、价格范围与收益率的三重组合",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "volume",
        "market_regime": "any",
        "complexity": "medium",
        "operator_deps": ["ts_rank"],
        "data_deps": ["volume", "close", "high", "low", "returns"]
    },
    {
        "name": "alpha_036",
        "source": "worldquant_101",
        "expression": "(((((2.21 * rank(correlation((close - open), delay(volume, 1), 15))) + (0.7 * rank((open - close)))) + (0.73 * rank(Ts_Rank(delay((-1 * returns), 6), 5)))) + rank(abs(correlation(vwap, adv20, 6)))) + (0.6 * rank((((sum(close, 200) / 200) - open) * (close - open)))))",
        "description": "多因子加权组合，包含价量相关性、日内收益、延迟收益、VWAP-成交量关系等",
        "category": "momentum",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "vwap",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["rank", "correlation", "delay", "ts_rank", "abs", "sum"],
        "data_deps": ["close", "open", "volume", "returns", "vwap", "adv20"]
    },
    {
        "name": "alpha_037",
        "source": "worldquant_101",
        "expression": "(rank(correlation(delay((open - close), 1), close, 200)) + rank((open - close)))",
        "description": "前日日内收益与收盘价长期相关性及当日日内收益的组合",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "long",
        "data_requirement": "price_only",
        "market_regime": "any",
        "complexity": "medium",
        "operator_deps": ["rank", "correlation", "delay"],
        "data_deps": ["open", "close"]
    },
    {
        "name": "alpha_038",
        "source": "worldquant_101",
        "expression": "(-1 * rank(Ts_Rank(close, 10))) * rank((close / open))",
        "description": "收盘价时序排名与日内收益率的组合，反转因子",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "price_only",
        "market_regime": "ranging",
        "complexity": "simple",
        "operator_deps": ["rank", "ts_rank"],
        "data_deps": ["close", "open"]
    },
    {
        "name": "alpha_039",
        "source": "worldquant_101",
        "expression": "((-1 * rank((delta(close, 7) * (1 - rank(decay_linear((volume / adv20), 9)))))) * (1 + rank(sum(returns, 250))))",
        "description": "7日价格变化、成交量衰减与长期累计收益的组合",
        "category": "momentum",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "volume",
        "market_regime": "trending",
        "complexity": "complex",
        "operator_deps": ["rank", "delta", "decay_linear", "sum"],
        "data_deps": ["close", "volume", "adv20", "returns"]
    },
    {
        "name": "alpha_040",
        "source": "worldquant_101",
        "expression": "((-1 * rank(stddev(high, 10))) * correlation(high, volume, 10))",
        "description": "高价波动率与高价-成交量相关性的组合",
        "category": "volatility",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "volatile",
        "complexity": "simple",
        "operator_deps": ["rank", "stddev", "correlation"],
        "data_deps": ["high", "volume"]
    },
    {
        "name": "alpha_041",
        "source": "worldquant_101",
        "expression": "(((high * low)^0.5) - vwap)",
        "description": "几何平均价与VWAP的偏离，检测价格失衡",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "intraday",
        "data_requirement": "vwap",
        "market_regime": "any",
        "complexity": "simple",
        "operator_deps": [],
        "data_deps": ["high", "low", "vwap"]
    },
    {
        "name": "alpha_042",
        "source": "worldquant_101",
        "expression": "(rank((vwap - close)) / rank((vwap + close)))",
        "description": "VWAP-收盘价偏离的归一化，delay-0因子",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "intraday",
        "data_requirement": "vwap",
        "market_regime": "ranging",
        "complexity": "simple",
        "operator_deps": ["rank"],
        "data_deps": ["vwap", "close"]
    },
    {
        "name": "alpha_043",
        "source": "worldquant_101",
        "expression": "(ts_rank((volume / adv20), 20) * ts_rank((-1 * delta(close, 7)), 8))",
        "description": "相对成交量与价格反向变化的时序排名组合",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "any",
        "complexity": "medium",
        "operator_deps": ["ts_rank", "delta"],
        "data_deps": ["volume", "adv20", "close"]
    },
    {
        "name": "alpha_044",
        "source": "worldquant_101",
        "expression": "(-1 * correlation(high, rank(volume), 5))",
        "description": "高价与成交量排名的负相关，识别价格拉升异常",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "any",
        "complexity": "simple",
        "operator_deps": ["correlation", "rank"],
        "data_deps": ["high", "volume"]
    },
    {
        "name": "alpha_045",
        "source": "worldquant_101",
        "expression": "(-1 * ((rank((sum(delay(close, 5), 20) / 20)) * correlation(close, volume, 2)) * rank(correlation(sum(close, 5), sum(close, 20), 2))))",
        "description": "延迟均线排名、价量相关性与均线相关性的三重组合",
        "category": "momentum",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "volume",
        "market_regime": "trending",
        "complexity": "complex",
        "operator_deps": ["rank", "sum", "delay", "correlation"],
        "data_deps": ["close", "volume"]
    },
    {
        "name": "alpha_046",
        "source": "worldquant_101",
        "expression": "((0.25 < (((delay(close, 20) - delay(close, 10)) / 10) - ((delay(close, 10) - close) / 10))) ? (-1 * 1) : (((((delay(close, 20) - delay(close, 10)) / 10) - ((delay(close, 10) - close) / 10)) < 0) ? 1 : ((-1 * 1) * (close - delay(close, 1)))))",
        "description": "均线斜率变化阈值判断，检测趋势加速/减速",
        "category": "momentum",
        "signal_type": "entry",
        "holding_period": "medium",
        "data_requirement": "price_only",
        "market_regime": "trending",
        "complexity": "complex",
        "operator_deps": ["delay"],
        "data_deps": ["close"]
    },
    {
        "name": "alpha_047",
        "source": "worldquant_101",
        "expression": "((((rank((1 / close)) * volume) / adv20) * ((high * rank((high - close))) / (sum(high, 5) / 5))) - rank((vwap - delay(vwap, 5))))",
        "description": "价格倒数、成交量、上影线与VWAP变化的复杂组合",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "vwap",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["rank", "sum", "delay"],
        "data_deps": ["close", "volume", "adv20", "high", "vwap"]
    },
    {
        "name": "alpha_048",
        "source": "worldquant_101",
        "expression": "IndNeutralize(((correlation(delta(close, 1), delta(delay(close, 1), 1), 250) * delta(close, 1)) / close), IndClass.subindustry) / sum(((delta(close, 1) / delay(close, 1))^2), 250)",
        "description": "行业中性化的价格自相关与收益率波动比，需要行业分类数据",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "long",
        "data_requirement": "industry",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["correlation", "delta", "delay", "sum", "indneutralize"],
        "data_deps": ["close", "industry"]
    },
    {
        "name": "alpha_049",
        "source": "worldquant_101",
        "expression": "(((((delay(close, 20) - delay(close, 10)) / 10) - ((delay(close, 10) - close) / 10)) < (-1 * 0.1)) ? 1 : ((-1 * 1) * (close - delay(close, 1))))",
        "description": "均线斜率下降阈值判断，趋势反转检测",
        "category": "mean_reversion",
        "signal_type": "entry",
        "holding_period": "medium",
        "data_requirement": "price_only",
        "market_regime": "trending",
        "complexity": "medium",
        "operator_deps": ["delay"],
        "data_deps": ["close"]
    },
    {
        "name": "alpha_050",
        "source": "worldquant_101",
        "expression": "(-1 * ts_max(rank(correlation(rank(volume), rank(vwap), 5)), 5))",
        "description": "成交量与VWAP排名相关性的最大值，识别价量异常",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "vwap",
        "market_regime": "any",
        "complexity": "medium",
        "operator_deps": ["ts_max", "rank", "correlation"],
        "data_deps": ["volume", "vwap"]
    },
    {
        "name": "alpha_051",
        "source": "worldquant_101",
        "expression": "(((((delay(close, 20) - delay(close, 10)) / 10) - ((delay(close, 10) - close) / 10)) < (-1 * 0.05)) ? 1 : ((-1 * 1) * (close - delay(close, 1))))",
        "description": "均线斜率下降阈值判断（更宽松），类似alpha_049",
        "category": "mean_reversion",
        "signal_type": "entry",
        "holding_period": "medium",
        "data_requirement": "price_only",
        "market_regime": "trending",
        "complexity": "medium",
        "operator_deps": ["delay"],
        "data_deps": ["close"]
    },
    {
        "name": "alpha_052",
        "source": "worldquant_101",
        "expression": "((((-1 * ts_min(low, 5)) + delay(ts_min(low, 5), 5)) * rank(((sum(returns, 240) - sum(returns, 20)) / 220))) * ts_rank(volume, 5))",
        "description": "5日最低价变化、长短期收益差与成交量时序排名的组合",
        "category": "momentum",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "volume",
        "market_regime": "trending",
        "complexity": "complex",
        "operator_deps": ["ts_min", "delay", "rank", "sum", "ts_rank"],
        "data_deps": ["low", "returns", "volume"]
    },
    {
        "name": "alpha_053",
        "source": "worldquant_101",
        "expression": "(-1 * delta((((close - low) - (high - close)) / (close - low)), 9))",
        "description": "下影线与上影线比率的变化，K线形态动量",
        "category": "price_pattern",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "price_only",
        "market_regime": "any",
        "complexity": "simple",
        "operator_deps": ["delta"],
        "data_deps": ["close", "low", "high"]
    },
    {
        "name": "alpha_054",
        "source": "worldquant_101",
        "expression": "((-1 * ((low - close) * (open^5))) / ((low - high) * (close^5)))",
        "description": "下影线与价格范围的非线性比率，delay-0因子",
        "category": "price_pattern",
        "signal_type": "alpha",
        "holding_period": "intraday",
        "data_requirement": "price_only",
        "market_regime": "any",
        "complexity": "medium",
        "operator_deps": [],
        "data_deps": ["low", "close", "open", "high"]
    },
    {
        "name": "alpha_055",
        "source": "worldquant_101",
        "expression": "(-1 * correlation(rank(((close - ts_min(low, 12)) / (ts_max(high, 12) - ts_min(low, 12)))), rank(volume), 6))",
        "description": "随机指标(KDJ)与成交量排名的负相关",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "ranging",
        "complexity": "medium",
        "operator_deps": ["correlation", "rank", "ts_min", "ts_max"],
        "data_deps": ["close", "low", "high", "volume"]
    },
    {
        "name": "alpha_056",
        "source": "worldquant_101",
        "expression": "(0 - (1 * (rank((sum(returns, 10) / sum(sum(returns, 2), 3))) * rank((returns * cap)))))",
        "description": "收益率滚动比与市值加权收益的组合，需要市值数据（行业类）",
        "category": "momentum",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "industry",
        "market_regime": "trending",
        "complexity": "medium",
        "operator_deps": ["rank", "sum"],
        "data_deps": ["returns", "cap"]
    },
    {
        "name": "alpha_057",
        "source": "worldquant_101",
        "expression": "(0 - (1 * ((close - vwap) / decay_linear(rank(ts_argmax(close, 30)), 2))))",
        "description": "VWAP偏离与30日最高价位置的衰减排名比",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "vwap",
        "market_regime": "ranging",
        "complexity": "medium",
        "operator_deps": ["decay_linear", "rank", "ts_argmax"],
        "data_deps": ["close", "vwap"]
    },
    {
        "name": "alpha_058",
        "source": "worldquant_101",
        "expression": "(-1 * Ts_Rank(decay_linear(correlation(IndNeutralize(vwap, IndClass.sector), volume, 3.92795), 7.89291), 5.50322))",
        "description": "行业中性化VWAP与成交量相关性的衰减时序排名",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "industry",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["ts_rank", "decay_linear", "correlation", "indneutralize"],
        "data_deps": ["vwap", "volume", "industry"]
    },
    {
        "name": "alpha_059",
        "source": "worldquant_101",
        "expression": "(-1 * Ts_Rank(decay_linear(correlation(IndNeutralize(((vwap * 0.728317) + (vwap * (1 - 0.728317))), IndClass.industry), volume, 4.25197), 16.2289), 8.19648))",
        "description": "行业中性化VWAP加权与成交量相关性的衰减时序排名",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "industry",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["ts_rank", "decay_linear", "correlation", "indneutralize"],
        "data_deps": ["vwap", "volume", "industry"]
    },
    {
        "name": "alpha_060",
        "source": "worldquant_101",
        "expression": "(0 - (1 * ((2 * scale(rank(((((close - low) - (high - close)) / (high - low)) * volume)))) - scale(rank(ts_argmax(close, 10))))))",
        "description": "成交量加权的K线位置与最高价位置的标准化差",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "any",
        "complexity": "medium",
        "operator_deps": ["scale", "rank", "ts_argmax"],
        "data_deps": ["close", "low", "high", "volume"]
    },
    {
        "name": "alpha_061",
        "source": "worldquant_101",
        "expression": "(rank((vwap - ts_min(vwap, 16.1219))) < rank(correlation(vwap, adv180, 17.9282)))",
        "description": "VWAP相对最低值与VWAP-成交量相关性的比较，布尔信号",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "vwap",
        "market_regime": "ranging",
        "complexity": "medium",
        "operator_deps": ["rank", "ts_min", "correlation"],
        "data_deps": ["vwap", "adv180"]
    },
    {
        "name": "alpha_062",
        "source": "worldquant_101",
        "expression": "((rank(correlation(vwap, sum(adv20, 22.4101), 9.91009)) < rank(((rank(open) + rank(open)) < (rank(((high + low) / 2)) + rank(high))))) * -1)",
        "description": "VWAP-成交量相关性与开盘价-高价关系的组合判断",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "vwap",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["rank", "correlation", "sum"],
        "data_deps": ["vwap", "adv20", "open", "high", "low"]
    },
    {
        "name": "alpha_063",
        "source": "worldquant_101",
        "expression": "((rank(decay_linear(delta(IndNeutralize(close, IndClass.industry), 2.25164), 8.22237)) - rank(decay_linear(correlation(((vwap * 0.318108) + (open * (1 - 0.318108))), sum(adv180, 37.2467), 13.557), 12.2883))) * -1)",
        "description": "行业中性化价格变化衰减与VWAP-开盘价加权相关性衰减的差",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "industry",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["rank", "decay_linear", "delta", "correlation", "sum", "indneutralize"],
        "data_deps": ["close", "vwap", "open", "adv180", "industry"]
    },
    {
        "name": "alpha_064",
        "source": "worldquant_101",
        "expression": "((rank(correlation(sum(((open * 0.178404) + (low * (1 - 0.178404))), 12.7054), sum(adv120, 12.7054), 16.6208)) < rank(delta(((((high + low) / 2) * 0.178404) + (vwap * (1 - 0.178404))), 3.69741))) * -1)",
        "description": "开盘-低价加权与成交量相关性与中间价-VWAP加权变化的比较",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "vwap",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["rank", "correlation", "sum", "delta"],
        "data_deps": ["open", "low", "high", "vwap", "adv120"]
    },
    {
        "name": "alpha_065",
        "source": "worldquant_101",
        "expression": "((rank(correlation(((open * 0.00817205) + (vwap * (1 - 0.00817205))), sum(adv60, 8.6911), 6.40374)) < rank((open - ts_min(open, 13.635)))) * -1)",
        "description": "开盘-VWAP加权与成交量相关性与开盘价相对最低值的比较",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "vwap",
        "market_regime": "ranging",
        "complexity": "medium",
        "operator_deps": ["rank", "correlation", "sum", "ts_min"],
        "data_deps": ["open", "vwap", "adv60"]
    },
    {
        "name": "alpha_066",
        "source": "worldquant_101",
        "expression": "((rank(decay_linear(delta(vwap, 3.51013), 7.23052)) + Ts_Rank(decay_linear(((((low * 0.96633) + (low * (1 - 0.96633))) - vwap) / (open - ((high + low) / 2))), 11.4157), 6.72611)) * -1)",
        "description": "VWAP变化衰减与低价-VWAP偏离比率衰减的时序排名组合",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "vwap",
        "market_regime": "ranging",
        "complexity": "complex",
        "operator_deps": ["rank", "decay_linear", "delta", "ts_rank"],
        "data_deps": ["vwap", "low", "open", "high"]
    },
    {
        "name": "alpha_067",
        "source": "worldquant_101",
        "expression": "((rank((high - ts_min(high, 2.14593)))^rank(correlation(IndNeutralize(vwap, IndClass.sector), IndNeutralize(adv20, IndClass.subindustry), 6.02936))) * -1)",
        "description": "高价相对最低值的幂次与行业中性化VWAP-成交量相关性",
        "category": "momentum",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "industry",
        "market_regime": "trending",
        "complexity": "complex",
        "operator_deps": ["rank", "ts_min", "correlation", "indneutralize"],
        "data_deps": ["high", "vwap", "adv20", "industry"]
    },
    {
        "name": "alpha_068",
        "source": "worldquant_101",
        "expression": "((Ts_Rank(correlation(rank(high), rank(adv15), 8.91644), 13.9333) < rank(delta(((close * 0.518371) + (low * (1 - 0.518371))), 1.06157))) * -1)",
        "description": "高价-成交量相关性时序排名与收盘-低价加权变化的比较",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "any",
        "complexity": "medium",
        "operator_deps": ["ts_rank", "correlation", "rank", "delta"],
        "data_deps": ["high", "adv15", "close", "low"]
    },
    {
        "name": "alpha_069",
        "source": "worldquant_101",
        "expression": "((rank(ts_max(delta(IndNeutralize(vwap, IndClass.industry), 2.72412), 4.79344))^Ts_Rank(correlation(((close * 0.490655) + (vwap * (1 - 0.490655))), adv20, 4.92416), 9.0615)) * -1)",
        "description": "行业中性化VWAP变化最大值的幂次与收盘-VWAP加权相关性时序排名",
        "category": "volatility",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "industry",
        "market_regime": "volatile",
        "complexity": "complex",
        "operator_deps": ["rank", "ts_max", "delta", "ts_rank", "correlation", "indneutralize"],
        "data_deps": ["vwap", "close", "adv20", "industry"]
    },
    {
        "name": "alpha_070",
        "source": "worldquant_101",
        "expression": "((rank(delta(vwap, 1.29456))^Ts_Rank(correlation(IndNeutralize(close, IndClass.industry), adv50, 17.8256), 17.9171)) * -1)",
        "description": "VWAP变化的幂次与行业中性化收盘价-成交量相关性时序排名",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "industry",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["rank", "delta", "ts_rank", "correlation", "indneutralize"],
        "data_deps": ["vwap", "close", "adv50", "industry"]
    },
    {
        "name": "alpha_071",
        "source": "worldquant_101",
        "expression": "max(Ts_Rank(decay_linear(correlation(Ts_Rank(close, 3.43976), Ts_Rank(adv180, 12.0647), 18.0175), 4.20501), 15.6948), Ts_Rank(decay_linear((rank(((low + open) - (vwap + vwap)))^2), 16.4662), 4.4388))",
        "description": "收盘价-成交量相关性衰减时序排名与开盘-VWAP偏离平方衰减时序排名的最大值",
        "category": "momentum",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "vwap",
        "market_regime": "trending",
        "complexity": "complex",
        "operator_deps": ["max", "ts_rank", "decay_linear", "correlation", "rank"],
        "data_deps": ["close", "adv180", "low", "open", "vwap"]
    },
    {
        "name": "alpha_072",
        "source": "worldquant_101",
        "expression": "(rank(decay_linear(correlation(((high + low) / 2), adv40, 8.93345), 10.1519)) / rank(decay_linear(correlation(Ts_Rank(vwap, 3.72469), Ts_Rank(volume, 18.5188), 6.86671), 2.95011)))",
        "description": "中间价-成交量相关性衰减排名与VWAP-成交量时序排名相关性衰减排名的比",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "vwap",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["rank", "decay_linear", "correlation", "ts_rank"],
        "data_deps": ["high", "low", "adv40", "vwap", "volume"]
    },
    {
        "name": "alpha_073",
        "source": "worldquant_101",
        "expression": "(max(rank(decay_linear(delta(vwap, 4.72775), 2.91864)), Ts_Rank(decay_linear(((delta(((open * 0.147155) + (low * (1 - 0.147155))), 2.03608) / ((open * 0.147155) + (low * (1 - 0.147155)))) * -1), 3.33829), 16.7411)) * -1)",
        "description": "VWAP变化衰减排名与开盘-低价加权收益率衰减时序排名的最大值",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "vwap",
        "market_regime": "ranging",
        "complexity": "complex",
        "operator_deps": ["max", "rank", "decay_linear", "delta", "ts_rank"],
        "data_deps": ["vwap", "open", "low"]
    },
    {
        "name": "alpha_074",
        "source": "worldquant_101",
        "expression": "((rank(correlation(close, sum(adv30, 37.4843), 15.1365)) < rank(correlation(rank(((high * 0.0261661) + (vwap * (1 - 0.0261661)))), rank(volume), 11.4791))) * -1)",
        "description": "收盘价-成交量相关性排名与高价-VWAP加权-成交量双排名相关性的比较",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "vwap",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["rank", "correlation", "sum"],
        "data_deps": ["close", "adv30", "high", "vwap", "volume"]
    },
    {
        "name": "alpha_075",
        "source": "worldquant_101",
        "expression": "(rank(correlation(vwap, volume, 4.24304)) < rank(correlation(rank(low), rank(adv50), 12.4413)))",
        "description": "VWAP-成交量相关性排名与低价-成交量双排名相关性排名的比较",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "vwap",
        "market_regime": "any",
        "complexity": "medium",
        "operator_deps": ["rank", "correlation"],
        "data_deps": ["vwap", "volume", "low", "adv50"]
    },
    {
        "name": "alpha_076",
        "source": "worldquant_101",
        "expression": "(max(rank(decay_linear(delta(vwap, 1.24383), 11.8259)), Ts_Rank(decay_linear(Ts_Rank(correlation(IndNeutralize(low, IndClass.sector), adv81, 8.14941), 19.569), 17.1543), 19.383)) * -1)",
        "description": "VWAP变化衰减排名与行业中性化低价-成交量相关性双时序排名衰减的最大值",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "industry",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["max", "rank", "decay_linear", "delta", "ts_rank", "correlation", "indneutralize"],
        "data_deps": ["vwap", "low", "adv81", "industry"]
    },
    {
        "name": "alpha_077",
        "source": "worldquant_101",
        "expression": "min(rank(decay_linear(((((high + low) / 2) + high) - (vwap + high)), 20.0451)), rank(decay_linear(correlation(((high + low) / 2), adv40, 3.1614), 5.64125)))",
        "description": "高价-VWAP偏离衰减排名与中间价-成交量相关性衰减排名的最小值",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "vwap",
        "market_regime": "ranging",
        "complexity": "medium",
        "operator_deps": ["min", "rank", "decay_linear", "correlation"],
        "data_deps": ["high", "low", "vwap", "adv40"]
    },
    {
        "name": "alpha_078",
        "source": "worldquant_101",
        "expression": "(rank(correlation(sum(((low * 0.352233) + (vwap * (1 - 0.352233))), 19.7428), sum(adv40, 19.7428), 6.83313))^rank(correlation(rank(vwap), rank(volume), 5.77492)))",
        "description": "低价-VWAP加权-成交量相关性排名的幂次，指数为VWAP-成交量双排名相关性排名",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "vwap",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["rank", "correlation", "sum"],
        "data_deps": ["low", "vwap", "adv40", "volume"]
    },
    {
        "name": "alpha_079",
        "source": "worldquant_101",
        "expression": "(rank(delta(IndNeutralize(((close * 0.60733) + (open * (1 - 0.60733))), IndClass.sector), 1.23438)) < rank(correlation(Ts_Rank(vwap, 3.60973), Ts_Rank(adv150, 9.18637), 14.6644)))",
        "description": "行业中性化收盘-开盘加权变化排名与VWAP-成交量双时序排名相关性排名的比较",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "industry",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["rank", "delta", "correlation", "ts_rank", "indneutralize"],
        "data_deps": ["close", "open", "vwap", "adv150", "industry"]
    },
    {
        "name": "alpha_080",
        "source": "worldquant_101",
        "expression": "((rank(Sign(delta(IndNeutralize(((open * 0.868128) + (high * (1 - 0.868128))), IndClass.industry), 4.04545)))^Ts_Rank(correlation(high, adv10, 5.11456), 5.53756)) * -1)",
        "description": "行业中性化开盘-高价加权变化符号排名的幂次，指数为高价-成交量相关性时序排名",
        "category": "momentum",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "industry",
        "market_regime": "trending",
        "complexity": "complex",
        "operator_deps": ["rank", "sign", "delta", "ts_rank", "correlation", "indneutralize"],
        "data_deps": ["open", "high", "adv10", "industry"]
    },
    {
        "name": "alpha_081",
        "source": "worldquant_101",
        "expression": "((rank(Log(product(rank((rank(correlation(vwap, sum(adv10, 49.6054), 8.47743))^4)), 14.9655))) < rank(correlation(rank(vwap), rank(volume), 5.07914))) * -1)",
        "description": "VWAP-成交量相关性排名4次幂乘积对数排名与VWAP-成交量双排名相关性排名的比较",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "vwap",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["rank", "log", "product", "correlation", "sum"],
        "data_deps": ["vwap", "adv10", "volume"]
    },
    {
        "name": "alpha_082",
        "source": "worldquant_101",
        "expression": "(min(rank(decay_linear(delta(open, 1.46063), 14.8717)), Ts_Rank(decay_linear(correlation(IndNeutralize(volume, IndClass.sector), ((open * 0.634196) + (open * (1 - 0.634196))), 17.4842), 6.92131), 13.4283)) * -1)",
        "description": "开盘价变化衰减排名与行业中性化成交量-开盘价相关性衰减时序排名的最小值",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "industry",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["min", "rank", "decay_linear", "delta", "ts_rank", "correlation", "indneutralize"],
        "data_deps": ["open", "volume", "industry"]
    },
    {
        "name": "alpha_083",
        "source": "worldquant_101",
        "expression": "((rank(delay(((high - low) / (sum(close, 5) / 5)), 2)) * rank(rank(volume))) / (((high - low) / (sum(close, 5) / 5)) / (vwap - close)))",
        "description": "延迟的价格范围-均线比与成交量双排名的积除以当前价格范围-均线比与VWAP偏离比",
        "category": "volatility",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "vwap",
        "market_regime": "volatile",
        "complexity": "complex",
        "operator_deps": ["rank", "delay", "sum"],
        "data_deps": ["high", "low", "close", "volume", "vwap"]
    },
    {
        "name": "alpha_084",
        "source": "worldquant_101",
        "expression": "SignedPower(Ts_Rank((vwap - ts_max(vwap, 15.3217)), 20.7127), delta(close, 4.96796))",
        "description": "VWAP相对最大值的时序排名的幂次，指数为收盘价变化",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "vwap",
        "market_regime": "ranging",
        "complexity": "medium",
        "operator_deps": ["signed_power", "ts_rank", "ts_max", "delta"],
        "data_deps": ["vwap", "close"]
    },
    {
        "name": "alpha_085",
        "source": "worldquant_101",
        "expression": "(rank(correlation(((high * 0.876703) + (close * (1 - 0.876703))), adv30, 9.61331))^rank(correlation(Ts_Rank(((high + low) / 2), 3.70596), Ts_Rank(volume, 10.1595), 7.11408)))",
        "description": "高价-收盘价加权-成交量相关性排名的幂次，指数为中间价-成交量双时序排名相关性排名",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["rank", "correlation", "ts_rank"],
        "data_deps": ["high", "close", "adv30", "low", "volume"]
    },
    {
        "name": "alpha_086",
        "source": "worldquant_101",
        "expression": "((Ts_Rank(correlation(close, sum(adv20, 14.7444), 6.00049), 20.4195) < rank(((open + close) - (vwap + open)))) * -1)",
        "description": "收盘价-成交量相关性时序排名与开盘-收盘-VWAP关系排名的比较",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "vwap",
        "market_regime": "ranging",
        "complexity": "medium",
        "operator_deps": ["ts_rank", "correlation", "sum", "rank"],
        "data_deps": ["close", "adv20", "open", "vwap"]
    },
    {
        "name": "alpha_087",
        "source": "worldquant_101",
        "expression": "(max(rank(decay_linear(delta(((close * 0.369701) + (vwap * (1 - 0.369701))), 1.91233), 2.65461)), Ts_Rank(decay_linear(abs(correlation(IndNeutralize(adv81, IndClass.industry), close, 13.4132)), 4.89768), 14.4535)) * -1)",
        "description": "收盘-VWAP加权变化衰减排名与行业中性化成交量-收盘价相关性绝对值衰减时序排名的最大值",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "industry",
        "market_regime": "ranging",
        "complexity": "complex",
        "operator_deps": ["max", "rank", "decay_linear", "delta", "ts_rank", "abs", "correlation", "indneutralize"],
        "data_deps": ["close", "vwap", "adv81", "industry"]
    },
    {
        "name": "alpha_088",
        "source": "worldquant_101",
        "expression": "min(rank(decay_linear(((rank(open) + rank(low)) - (rank(high) + rank(close))), 8.06882)), Ts_Rank(decay_linear(correlation(Ts_Rank(close, 8.44728), Ts_Rank(adv60, 20.6966), 8.01266), 6.65053), 2.61957))",
        "description": "开盘-低价与高价-收盘价排名差的衰减排名与收盘-成交量双时序排名相关性衰减时序排名的最小值",
        "category": "price_pattern",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "volume",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["min", "rank", "decay_linear", "ts_rank", "correlation"],
        "data_deps": ["open", "low", "high", "close", "adv60"]
    },
    {
        "name": "alpha_089",
        "source": "worldquant_101",
        "expression": "(Ts_Rank(decay_linear(correlation(((low * 0.967285) + (low * (1 - 0.967285))), adv10, 6.94279), 5.51607), 3.79744) - Ts_Rank(decay_linear(delta(IndNeutralize(vwap, IndClass.industry), 3.48158), 10.1466), 15.3012))",
        "description": "低价-成交量相关性衰减时序排名与行业中性化VWAP变化衰减时序排名的差",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "industry",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["ts_rank", "decay_linear", "correlation", "delta", "indneutralize"],
        "data_deps": ["low", "adv10", "vwap", "industry"]
    },
    {
        "name": "alpha_090",
        "source": "worldquant_101",
        "expression": "((rank((close - ts_max(close, 4.66719)))^Ts_Rank(correlation(IndNeutralize(adv40, IndClass.subindustry), low, 5.38375), 3.21856)) * -1)",
        "description": "收盘价相对最大值排名的幂次，指数为行业中性化成交量-低价相关性时序排名",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "industry",
        "market_regime": "ranging",
        "complexity": "complex",
        "operator_deps": ["rank", "ts_max", "ts_rank", "correlation", "indneutralize"],
        "data_deps": ["close", "adv40", "low", "industry"]
    },
    {
        "name": "alpha_091",
        "source": "worldquant_101",
        "expression": "((Ts_Rank(decay_linear(decay_linear(correlation(IndNeutralize(close, IndClass.industry), volume, 9.74928), 16.398), 3.83219), 4.8667) - rank(decay_linear(correlation(vwap, adv30, 4.01303), 2.6809))) * -1)",
        "description": "行业中性化收盘-成交量相关性双衰减时序排名与VWAP-成交量相关性衰减排名的差",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "industry",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["ts_rank", "decay_linear", "correlation", "rank", "indneutralize"],
        "data_deps": ["close", "volume", "vwap", "adv30", "industry"]
    },
    {
        "name": "alpha_092",
        "source": "worldquant_101",
        "expression": "min(Ts_Rank(decay_linear(((((high + low) / 2) + close) < (low + open)), 14.7221), 18.8683), Ts_Rank(decay_linear(correlation(rank(low), rank(adv30), 7.58555), 6.94024), 6.80584))",
        "description": "中间价-收盘与低价-开盘比较的衰减时序排名与低价-成交量双排名相关性衰减时序排名的最小值",
        "category": "price_pattern",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "volume",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["min", "ts_rank", "decay_linear", "correlation", "rank"],
        "data_deps": ["high", "low", "close", "open", "adv30"]
    },
    {
        "name": "alpha_093",
        "source": "worldquant_101",
        "expression": "(Ts_Rank(decay_linear(correlation(IndNeutralize(vwap, IndClass.industry), adv81, 17.4193), 19.848), 7.54455) / rank(decay_linear(delta(((close * 0.524434) + (vwap * (1 - 0.524434))), 2.77377), 16.2664)))",
        "description": "行业中性化VWAP-成交量相关性衰减时序排名除以收盘-VWAP加权变化衰减排名",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "industry",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["ts_rank", "decay_linear", "correlation", "rank", "delta", "indneutralize"],
        "data_deps": ["vwap", "adv81", "close", "industry"]
    },
    {
        "name": "alpha_094",
        "source": "worldquant_101",
        "expression": "((rank((vwap - ts_min(vwap, 11.5783)))^Ts_Rank(correlation(Ts_Rank(vwap, 19.6462), Ts_Rank(adv60, 4.02992), 18.0926), 2.70756)) * -1)",
        "description": "VWAP相对最小值排名的幂次，指数为VWAP-成交量双时序排名相关性时序排名",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "vwap",
        "market_regime": "ranging",
        "complexity": "complex",
        "operator_deps": ["rank", "ts_min", "ts_rank", "correlation"],
        "data_deps": ["vwap", "adv60"]
    },
    {
        "name": "alpha_095",
        "source": "worldquant_101",
        "expression": "(rank((open - ts_min(open, 12.4105))) < Ts_Rank((rank(correlation(sum(((high + low) / 2), 19.1351), sum(adv40, 19.1351), 12.8742))^5), 11.7584))",
        "description": "开盘价相对最小值排名与中间价-成交量相关性排名5次幂时序排名的比较",
        "category": "momentum",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "volume",
        "market_regime": "trending",
        "complexity": "complex",
        "operator_deps": ["rank", "ts_min", "ts_rank", "correlation", "sum"],
        "data_deps": ["open", "high", "low", "adv40"]
    },
    {
        "name": "alpha_096",
        "source": "worldquant_101",
        "expression": "(max(Ts_Rank(decay_linear(correlation(rank(vwap), rank(volume), 3.83878), 4.16783), 8.38151), Ts_Rank(decay_linear(Ts_ArgMax(correlation(Ts_Rank(close, 7.45404), Ts_Rank(adv60, 4.13242), 3.65459), 12.6556), 14.0365), 13.4143)) * -1)",
        "description": "VWAP-成交量双排名相关性衰减时序排名与收盘-成交量双时序排名相关性最大值位置衰减时序排名的最大值",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "vwap",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["max", "ts_rank", "decay_linear", "correlation", "rank", "ts_argmax"],
        "data_deps": ["vwap", "volume", "close", "adv60"]
    },
    {
        "name": "alpha_097",
        "source": "worldquant_101",
        "expression": "((rank(decay_linear(delta(IndNeutralize(((low * 0.721001) + (vwap * (1 - 0.721001))), IndClass.industry), 3.3705), 20.4523)) - Ts_Rank(decay_linear(Ts_Rank(correlation(Ts_Rank(low, 7.87871), Ts_Rank(adv60, 17.255), 4.97547), 18.5925), 15.7152), 6.71659)) * -1)",
        "description": "行业中性化低价-VWAP加权变化衰减排名与低价-成交量三重时序排名相关性衰减时序排名的差",
        "category": "mean_reversion",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "industry",
        "market_regime": "ranging",
        "complexity": "complex",
        "operator_deps": ["rank", "decay_linear", "delta", "ts_rank", "correlation", "indneutralize"],
        "data_deps": ["low", "vwap", "adv60", "industry"]
    },
    {
        "name": "alpha_098",
        "source": "worldquant_101",
        "expression": "(rank(decay_linear(correlation(vwap, sum(adv5, 26.4719), 4.58418), 7.18088)) - rank(decay_linear(Ts_Rank(Ts_ArgMin(correlation(rank(open), rank(adv15), 20.8187), 8.62571), 6.95668), 8.07206)))",
        "description": "VWAP-成交量相关性衰减排名与开盘-成交量双排名相关性最小值位置时序排名衰减排名的差",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "short",
        "data_requirement": "vwap",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["rank", "decay_linear", "correlation", "sum", "ts_rank", "ts_argmin"],
        "data_deps": ["vwap", "adv5", "open", "adv15"]
    },
    {
        "name": "alpha_099",
        "source": "worldquant_101",
        "expression": "((rank(correlation(sum(((high + low) / 2), 19.8975), sum(adv60, 19.8975), 8.8136)) < rank(correlation(low, volume, 6.28259))) * -1)",
        "description": "中间价-成交量相关性排名与低价-成交量相关性排名的比较",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "volume",
        "market_regime": "any",
        "complexity": "medium",
        "operator_deps": ["rank", "correlation", "sum"],
        "data_deps": ["high", "low", "adv60", "volume"]
    },
    {
        "name": "alpha_100",
        "source": "worldquant_101",
        "expression": "(0 - (1 * (((1.5 * scale(indneutralize(indneutralize(rank(((((close - low) - (high - close)) / (high - low)) * volume)), IndClass.subindustry), IndClass.subindustry))) - scale(indneutralize((correlation(close, rank(adv20), 5) - rank(ts_argmin(close, 30))), IndClass.subindustry))) * (volume / adv20))))",
        "description": "双重行业中性化的K线位置-成交量排名与收盘-成交量相关性-最低价位置差的标准化，加权成交量比",
        "category": "volume",
        "signal_type": "alpha",
        "holding_period": "medium",
        "data_requirement": "industry",
        "market_regime": "any",
        "complexity": "complex",
        "operator_deps": ["scale", "indneutralize", "rank", "correlation", "ts_argmin"],
        "data_deps": ["close", "low", "high", "volume", "adv20", "industry"]
    },
    {
        "name": "alpha_101",
        "source": "worldquant_101",
        "expression": "((close - open) / ((high - low) + 0.001))",
        "description": "日内收益与日内波动的比率，简单的K线强度因子",
        "category": "price_pattern",
        "signal_type": "alpha",
        "holding_period": "intraday",
        "data_requirement": "price_only",
        "market_regime": "any",
        "complexity": "simple",
        "operator_deps": [],
        "data_deps": ["close", "open", "high", "low"]
    },
]

# Category statistics
CATEGORY_STATS = {
    "momentum": 16,
    "mean_reversion": 25,
    "volatility": 6,
    "volume": 43,
    "price_pattern": 11,
}

# Holding period distribution
HOLDING_PERIOD_STATS = {
    "intraday": 4,  # 42, 48, 53, 54
    "short": 62,
    "medium": 33,
    "long": 2,
}

# Data requirement distribution
DATA_REQUIREMENT_STATS = {
    "price_only": 26,
    "volume": 40,
    "vwap": 16,
    "industry": 19,
}

# Complexity distribution
COMPLEXITY_STATS = {
    "simple": 12,
    "medium": 42,
    "complex": 47,
}
