# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: freqsearch/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'freqsearch/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x66reqsearch/v1/common.proto\x12\rfreqsearch.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"4\n\x11PaginationRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"_\n\x12PaginationResponse\x12\x13\n\x0btotal_count\x18\x01 \x01(\x05\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x11\n\tpage_size\x18\x03 \x01(\x05\x12\x13\n\x0btotal_pages\x18\x04 \x01(\x05\"_\n\tTimeRange\x12)\n\x05start\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x14\n\x12HealthCheckRequest\"\xac\x01\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x42\n\x08services\x18\x03 \x03(\x0b\x32\x30.freqsearch.v1.HealthCheckResponse.ServicesEntry\x1a/\n\rServicesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01*\xa2\x01\n\tJobStatus\x12\x1a\n\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n\x12JOB_STATUS_PENDING\x10\x01\x12\x16\n\x12JOB_STATUS_RUNNING\x10\x02\x12\x18\n\x14JOB_STATUS_COMPLETED\x10\x03\x12\x15\n\x11JOB_STATUS_FAILED\x10\x04\x12\x18\n\x14JOB_STATUS_CANCELLED\x10\x05*\xaf\x01\n\x0e\x41pprovalStatus\x12\x1f\n\x1b\x41PPROVAL_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x41PPROVAL_STATUS_PENDING\x10\x01\x12\x1c\n\x18\x41PPROVAL_STATUS_APPROVED\x10\x02\x12\x1c\n\x18\x41PPROVAL_STATUS_REJECTED\x10\x03\x12#\n\x1f\x41PPROVAL_STATUS_NEEDS_ITERATION\x10\x04\x42MZKgithub.com/saltfish/freqsearch/go-backend/pkg/pb/freqsearch/v1;freqsearchv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'freqsearch.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZKgithub.com/saltfish/freqsearch/go-backend/pkg/pb/freqsearch/v1;freqsearchv1'
  _globals['_HEALTHCHECKRESPONSE_SERVICESENTRY']._loaded_options = None
  _globals['_HEALTHCHECKRESPONSE_SERVICESENTRY']._serialized_options = b'8\001'
  _globals['_JOBSTATUS']._serialized_start=524
  _globals['_JOBSTATUS']._serialized_end=686
  _globals['_APPROVALSTATUS']._serialized_start=689
  _globals['_APPROVALSTATUS']._serialized_end=864
  _globals['_PAGINATIONREQUEST']._serialized_start=78
  _globals['_PAGINATIONREQUEST']._serialized_end=130
  _globals['_PAGINATIONRESPONSE']._serialized_start=132
  _globals['_PAGINATIONRESPONSE']._serialized_end=227
  _globals['_TIMERANGE']._serialized_start=229
  _globals['_TIMERANGE']._serialized_end=324
  _globals['_HEALTHCHECKREQUEST']._serialized_start=326
  _globals['_HEALTHCHECKREQUEST']._serialized_end=346
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=349
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=521
  _globals['_HEALTHCHECKRESPONSE_SERVICESENTRY']._serialized_start=474
  _globals['_HEALTHCHECKRESPONSE_SERVICESENTRY']._serialized_end=521
# @@protoc_insertion_point(module_scope)
